name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: pacextractor
      run: gcc -march=armv7-a -static -o pacextractor pacextractor.c
    - uses: actions/upload-artifact@v4
      with:
         name: pacextractor
         path: pacextractor
         
