name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libs
      run: sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
    - name: make
      run: make pacextractor
    - name: pacextractor
      run: arm-linux-gnueabi-gcc -static -o pacextractor pacextractor.c
    - uses: actions/upload-artifact@v4
      with:
         name: pacextractor
         path: pacextractor
         
