name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: istall
      run: sudo apt-get install gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-arm-none-eabi
    - name: pacextractor
      run: arm-none-eabi -g -ggdb -Wall -march=armv7-a -static -s -o pacextractor pacextractor.c
    - uses: actions/upload-artifact@v4
      with:
         name: pacextractor
         path: pacextractor
         
